### ISSUE TITLE
Change of naming format

### ISSUE THREAD

**Issue by KaiyangZhou** [Yu-Wu/DukeMTMC-VideoReID#1]
Hello Yu,

I notice that the naming format of images has been changed by adding an underscore, e.g. from '0001C6F0099X30823.jpg' to '0001_C6_F0099_X30823.jpg'. I am wondering if any changes are made to the images themselves (or just the names)?

**Comment by Yu-Wu** [comment]
@KaiyangZhou 

Hi Kaiyang,

Sorry for the later reply. The naming format of images has been changed as suggested by the author of the DukeMTMC dataset. Only the image names were changed, the image contents are kept **unchanged**. 

Sorry for the inconvenience.

**Comment by KaiyangZhou** [comment]
thanks for your confirmation.
