### ISSUE TITLE
About the metric protocal

### ISSUE THREAD

**Issue by JaHangirYin** [Yu-Wu/DukeMTMC-VideoReID#3]
DukeMTMC-VideoReID is a video-based reid dataset. And is its metric protocol same with DukeMTMC-reID， which is image-based reid dataset?

**Comment by Yu-Wu** [comment]
@JaHangirYin  Thanks for your interest.

Yes. The metric protocol is the same (i.e., the retrieval performances,  CMC rank and mAP).
Acturally, the DukeMTMC-VideoReID is designed similarly to the MARS video re-id dataset. All is the same except for the visual content. You may probably treat it the same as MARS.

**Comment by JaHangirYin** [comment]
"During testing, a video for each ID is used as the query and the remaining videos are placed in the gallery."
Testing set contains  2,636 videos which was divided into query and gallery. In testing stage, there are totally 2,636 features. Is it?

**Comment by Yu-Wu** [comment]
@JaHangirYin 

YES.
This is the common evaluation way for all the video-based person re-ID.

**Comment by JaHangirYin** [comment]
Thank you~~
