### ISSUE TITLE
DukeMTMC数据集咨询

### ISSUE THREAD

**Issue by donghaiwang** [Yu-Wu/DukeMTMC-VideoReID#4]
您好，我看到DukeMTMC-VideoReID和DukeMTMC数据集的官方网站都不提供下载了，请问我在研究中的论文还可以使用这两个数据集进行验证和测试吗，是否会有版权等因素的危险，谢谢~

**Comment by Yu-Wu** [comment]
@donghaiwang 

任何学术用途使用这两个数据集都是允许的。因此是可以在论文中使用的，没有版权风险。

现在只是不提供公开的下载链接，不代表数据是非法的

**Comment by Mickeybaby** [comment]
@Yu-Wu 
您好，您提供的下载地址我打不开，是现在不能下载了吗

**Comment by Yu-Wu** [comment]
@Mickeybaby 
是的，应主办方要求，我们下线了这个数据集的公开下载方式。

**Comment by Mickeybaby** [comment]
@Yu-Wu 
您好，那我现在要怎么样才能拿到这个数据集呢？我是研究生，想用来做实验发论文的。
