### ISSUE TITLE
DukeMTMCT数据问题咨询

### ISSUE THREAD

**Issue by donghaiwang** [Yu-Wu/DukeMTMC-VideoReID#6]
您好，我最近在做MTMCT实验的时候，发现数据集中测试集的ground truth没有，官方链接也已经失效，请问你有这个数据吗，如果有的话麻烦发送给我或者提供能够下载的链接，万分感谢~

原来测试集缺少的两个ground truth链接为：
http://vision.cs.duke.edu/DukeMTMC/data/ground_truth/testData.mat
http://vision.cs.duke.edu/DukeMTMC/data/ground_truth/testHardData.mat

**Comment by Yu-Wu** [comment]
Sorry that we do not have these data, either.

**Comment by 92ypli** [comment]
请问你们还有数据集吗

**Comment by nerddd** [comment]
同求
